### ISSUE TITLE
Could not start `Application` (example from docs)

### ISSUE THREAD

**Issue by nichita-pasecinic** [peburrows/goth#148]
Error:
```
** (Mix) Could not start application goth: Goth.start(:normal, []) returned an error: shutdown: failed to start child: Goth.Config
    ** (EXIT) an exception was raised:
        ** (RuntimeError)  Failed to retrieve project data from GCE internal metadata service.
                   Either you haven't configured your GCP credentials, you aren't running on GCE, or both.
                   Please see README.md for instructions on configuring your credentials.
            (goth 1.2.0) lib/goth/config.ex:182: Goth.Config.determine_project_id/2
            (goth 1.2.0) lib/goth/config.ex:73: anonymous fn/2 in Goth.Config.load_and_init/1
            (elixir 1.14.0) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
            (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
            (elixir 1.14.0) lib/enum.ex:2480: Enum.map/2
            (goth 1.2.0) lib/goth/config.ex:71: Goth.Config.load_and_init/1
            (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
            (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
            (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

```elixir
credentials =
      "service_account.json"
      |> File.read!()
      |> Jason.decode!()

source = {:service_account, credentials} # => correct service account credentials here

# inside children list
{Goth, name: Guava.Goth, source: source}
```

**Comment by nichita-pasecinic** [comment]
I think it fails at the first Token.fetch with the default_scope, because I don't have it configured in Google console, so how it would be possible to omit default token fetch on application boot, or how to change the default scope ?

**Comment by nichita-pasecinic** [comment]
sometimes I do get this error

```
** (Mix) Could not start application guava: exited in: Guava.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Goth was given as a child to a supervisor
but it does not implement child_spec/1.

If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: Goth,
      start: {Goth, :start_link, [arg1, arg2]}
    }
```

**Comment by nichita-pasecinic** [comment]
damn, all good, Just used an older version of the library

On ` {:goth, "~> 1.3"}` works perfectly! Thx for the lib 😄
